---
apiVersion: v1
kind: Namespace
metadata:
  name: target
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: target-app-svc-acc
  namespace: target
---
apiVersion: v1
kind: Service
metadata:
  name: target-app-service
  namespace: target
spec:
  type: NodePort
  selector:
    app: target-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-app
  namespace: target
spec:
  replicas: 1
  selector:
    matchLabels:
      app: target-app
  template:
    metadata:
      labels:
        app: target-app
    spec:
      serviceAccountName: target-app-svc-acc
      containers:
      - name: target-app-container
        image: quincycheng/killercoda-http-authn-server:latest
        ports:
        - containerPort: 80
